spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myDB
    username: postgres
    password: manager
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
